# This rule is not used by the project storagebase-studio-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to studio.storagebase.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: storagebase-studio-operator
    app.kubernetes.io/managed-by: kustomize
  name: storagebasestudio-viewer-role
rules:
- apiGroups:
  - studio.storagebase.org
  resources:
  - storagebasestudios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - studio.storagebase.org
  resources:
  - storagebasestudios/status
  verbs:
  - get
